name: gh_pages

on:
  push:
    branches:
      - hugo

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Run Scrip
      run: |
        git checkout hugo
        ls -la
